import com.sslcf.AppConfig

plugins {
    alias(libs.plugins.androidLibrary)
    alias(libs.plugins.kotlinAndroid)
}

android {
    namespace = AppConfig.LIBRARY_NAMESPACE
    compileSdk = AppConfig.COMPILE_SDK

    defaultConfig {
        minSdk = AppConfig.MIN_SDK
        targetSdk = AppConfig.TARGET_SDK

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles = ["consumer-rules.pro"]
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.toVersion(AppConfig.JAVA_VERSION_INT)
        targetCompatibility = JavaVersion.toVersion(AppConfig.JAVA_VERSION_INT)
    }

    kotlinOptions {
        jvmTarget = AppConfig.JAVA_VERSION
    }
}

dependencies {
    // AndroidX Core
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.androidx.material

    // Lifecycle
    implementation libs.androidx.lifecycle.runtime.ktx

    // DataStore
    implementation libs.androidx.datastore.preferences

    // Networking
    implementation libs.okhttp
    implementation libs.retrofit

    // JSON Processing
    implementation libs.gson
    implementation libs.json.path

    // Testing
    testImplementation libs.junit
    testImplementation libs.androidx.test.ext.junit
    testImplementation libs.androidx.arch.core
    testImplementation libs.mockk
    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.androidx.test.espresso.core
}